name: 'Wreadle'
description: 'Play Wordle in GitHub readme'
inputs:
  # state -> from readme
  # move -> from event payload
  # event type -> from ??
  # baseurl from -> /dispatch/owner/repo/event -> env var and event type
  # imageurl base -> hardcode
  # readme file -> input
  readme:
    description: 'path/name of the readme file'
    required: false
    default: 'README.md'
  tag:
    description: 'tag to identify wordle'
    required: false
    default: 'wreadle'
  serverUrl:
    description: 'server for triggering workflows'
    required: false
    default: 'https://wreadle.02420.dev'
runs:
  using: 'node16'
  main: 'dist/cjs/actions.js'
