name: 'Wreadle'
description: 'Play Wordle in GitHub readme'
branding:
  icon: 'grid'
  color: 'green'
inputs:
  readme:
    description: 'path/name of the readme file'
    required: false
    default: 'README.md'
  tag:
    description: 'tag to identify wordle'
    required: false
    default: 'wreadle'
  serverUrl:
    description: 'server for triggering workflows'
    required: false
    default: 'https://wreadle.02420.dev'
runs:
  using: 'node16'
  main: 'dist/cjs/actions.js'
